apiVersion: apps/v1
kind: Deployment
metadata:
  name: drone
spec:
  replicas: 1
  selector:
    matchLabels:
      app: drone
  template:
    spec:
      containers:
        - name: drone
          image: drone/drone
          ports:
            - name: http
              containerPort: 80
          env:
            - name: DRONE_KUBERNETES_ENABLED
              value: "true"
            - name: DRONE_KUBERNETES_NAMESPACE
              value: tools
            - name: DRONE_GITHUB_SERVER
              value: https://github.com
            - name: DRONE_SERVER_HOST
              value: drone.expected.sh
            - name: DRONE_SERVER_PROTO
              value: http
            - name: DRONE_REPOSITORY_FILTER
              value: expectedsh
            - name: DRONE_USER_FILTER
              value: expectedsh
          envFrom:
            - secretRef:
                name: drone
          resources:
            limits:
              cpu: 100m
              memory: 256Mi
            requests:
              cpu: 100m
              memory: 128Mi
