apiVersion: apps/v1
kind: Deployment
metadata:
  name: drone
  namespace: tools
  labels:
    app: drone
spec:
  replicas: 1
  selector:
    matchLabels:
      app: drone
  template:
    metadata:
      labels:
        app: drone
    spec:
      containers:
        - name: drone
          image: drone/drone:1.0.0-rc.3
          ports:
            - name: http
              containerPort: 80
          env:
            - name: DRONE_KUBERNETES_ENABLED
              value: "true"
            - name: DRONE_KUBERNETES_NAMESPACE
              value: tools
            - name: DRONE_GITHUB_SERVER
              value: https://github.com
            - name: DRONE_GITHUB_CLIENT_ID
              value: 1f5ac906f128bc5e3b43
            - name: DRONE_GITHUB_CLIENT_SECRET
              value: 9df8f9160c0ce7ebce0160455ee5940629832674
            - name: DRONE_RPC_SECRET
              value: 9c3921e3e748aff725d2e16ef31fbc42
            - name: DRONE_SERVER_HOST
              value: drone.expected.sh
            - name: DRONE_SERVER_PROTO
              value: http
            - name: DRONE_REPOSITORY_FILTER
              value: expectedsh
            - name: DRONE_USER_FILTER
              value: expectedsh
          resources:
            limits:
              cpu: 100m
              memory: 256Mi
            requests:
              cpu: 100m
              memory: 128Mi
