namespace: tools
commonLabels:
  app: drone
resources:
  - account.yaml
  - deployment.yaml
  - ingress.yaml
  - service.yaml
secretGenerator:
  - name: drone
    commands:
      DRONE_GITHUB_CLIENT_ID: "printf ${DRONE_CLIENT_ID}"
      DRONE_GITHUB_CLIENT_SECRET: "printf ${DRONE_CLIENT_SECRET}"
      DRONE_RPC_SECRET: "printf ${DRONE_SECRET}"
imageTags:
  - name: drone/drone
    newTag: 1.0.0-rc.5
