apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: traefik
spec:
  selector:
    matchLabels:
      app: traefik
  template:
    metadata:
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8080"
    spec:
      terminationGracePeriodSeconds: 60
      serviceAccountName: traefik
      hostNetwork: true
      containers:
        - name: traefik
          image: traefik
          args:
            - --configfile=/etc/traefik/traefik.toml
          volumeMounts:
            - name: config
              mountPath: /etc/traefik
          ports:
            - name: http
              containerPort: 80
            - name: https
              containerPort: 443
          readinessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 30
            timeoutSeconds: 30
          livenessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 30
            timeoutSeconds: 30
      volumes:
        - name: config
          configMap:
            name: traefik
