namespace: tools
commonLabels:
  app: traefik
resources:
  - account.yaml
  - deployment.yaml
configMapGenerator:
  - name: traefik
    files:
      - config/traefik.toml
imageTags:
  - name: traefik
    newTag: latest
