---
- name: Generate traefik rules
  become: true
  template:
    src: "templates/{{item}}.toml.j2"
    dest: "/etc/traefik/rules/{{item}}.toml"
    owner: traefik
    group: traefik
  with_items:
    - consul
    - nomad
    - drone
- name: Run postgres
  docker_container:
    name: postgres
    image: postgres:alpine
    restart_policy: always
    volumes:
      - /var/lib/postgresql:/var/lib/postgresql/data
    env:
      POSTGRES_USER: drone
      POSTGRES_PASSWORD: drone
- name: Run drone
  docker_container:
    name: drone
    image: "drone/drone:{{drone_version}}"
    restart_policy: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 8081:80
    links:
      - postgres
    env:
      DRONE_GITHUB_SERVER: https://github.com
      DRONE_GITHUB_CLIENT_ID: "{{drone_github_client_id}}"
      DRONE_GITHUB_CLIENT_SECRET: "{{drone_github_client_secret}}"
      DRONE_RUNNER_CAPACITY: "2"
      DRONE_SERVER_HOST: "drone.{{domain}}"
      DRONE_SERVER_PROTO: http
      DRONE_REPOSITORY_FILTER: expectedsh
      DRONE_USER_FILTER: expectedsh
      DRONE_ADMIN: remicaumette
      DRONE_DATABASE_DRIVER: postgres
      DRONE_DATABASE_DATASOURCE: postgres://drone:drone@postgres/drone?sslmode=disable
