kind: pipeline
name: default
steps:
  - name: deploy
    image: alpine
    secrets:
      - DIGITALOCEAN_TOKEN
      - CLUSTER_ID
    environment:
      - KUBECONFIG=/kubeconfig
    commands:
      - apk --no-cache add curl gettext
      - curl https://storage.googleapis.com/kubernetes-release/release/v1.13.3/bin/linux/amd64/kubectl -o /usr/bin/kubectl
      - chmod +x /usr/bin/kubectl
      - curl https://github.com/kubernetes-sigs/kustomize/releases/download/v2.0.1/kustomize_2.0.1_linux_amd64 -o /usr/bin/kustomize
      - chmod +x /usr/bin/kustomize
      - 'curl -X GET -H "Content-Type: application/json" -H "Authorization: Bearer $DIGITALOCEAN_TOKEN" https://api.digitalocean.com/v2/kubernetes/clusters/$CLUSTER_ID/kubeconfig -o /kubeconfig'
      - sleep 7200
  - name: kube
    image: vallard/drone-kube
    template: ./kubernetes/traefik/namespace.yaml
  - name: slack
    image: plugins/slack
    settings:
      webhook:
        from_secret: SLACK_WEBHOOK
      channel: chatbot
    when:
      status:
        - success
        - failure
trigger:
  branch:
    - master
  event:
    - push
