apiVersion: v1
kind: ConfigMap
metadata:
  name: alert-manager
  namespace: monitoring
  labels:
    app: alert-manager
data:
  alertmanager.yaml: |
    global: null
    receivers:
      - name: slack
        slack_configs:
          - api_url: https://hooks.slack.com/services/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
            channel: '#alerts'
    route:
      group_interval: 5m
      group_wait: 10s
      receiver: slack
      repeat_interval: 3h
