apiVersion: apps/v1
kind: Deployment
metadata:
  name: alert-manager
  namespace: monitoring
  labels:
    app: alert-manager
spec:
  replicas: 1
  selector:
    matchLabels:
      app: alert-manager
  template:
    metadata:
      labels:
        app: alert-manager
    spec:
      securityContext:
        fsGroup: 2000
        runAsNonRoot: true
        runAsUser: 1000
      containers:
        - name: alert-manager
          image: prom/alertmanager
          ports:
            - name: http
              containerPort: 9093
          volumeMounts:
            - name: config
              mountPath: /etc/alertmanager
            - name: alert-manager
              mountPath: /var/alertmanager
          args:
            - --config.file=/etc/alertmanager/alertmanager.yaml
            - --storage.path=/var/alertmanager
            - --web.external-url=/
          resources:
            limits:
              cpu: 10m
              memory: 128Mi
            requests:
              cpu: 10m
              memory: 64Mi
      volumes:
        - name: config
          configMap:
            name: alert-manager
        - name: alert-manager
          persistentVolumeClaim:
            claimName: alert-manager
