apiVersion: v1
kind: Service
metadata:
  name: alert-manager
  annotations:
    prometheus.io/scrape: "true"
spec:
  type: ClusterIP
  selector:
    app: alert-manager
  ports:
    - name: http
      port: 80
      targetPort: http
