apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: alert-manager
  namespace: monitoring
  labels:
    app: alert-manager
spec:
  resources:
    requests:
      storage: 1Gi
  accessModes:
    - ReadWriteOnce
