namespace: monitoring
commonLabels:
  app: kube-state-metrics
resources:
  - account.yaml
  - deployment.yaml
  - service.yaml
imageTags:
  - name: quay.io/coreos/kube-state-metrics
    newTag: latest
