apiVersion: 1
deleteDatasources:
  - name: Prometheus
    orgId: 1
datasources:
  - name: Prometheus
    type: prometheus
    orgId: 1
    url: http://prometheus
    access: proxy
    isDefault: true
    editable: true
