---
- name: Download traefik
  become: true
  get_url:
    url: "https://github.com/containous/traefik/releases/download/v{{traefik_version}}/traefik_linux-amd64"
    dest: /usr/local/bin/traefik
    mode: 0755
- name: Install traefik service
  become: true
  copy:
    src: files/traefik.service
    dest: /etc/systemd/system/traefik.service
- name: Create traefik group
  become: true
  group:
    name: traefik
    state: present
- name: Create traefik user
  become: true
  user:
    name: traefik
    group: traefik
- name: Add traefik to docker group
  become: true
  user:
    name: traefik
    groups: docker
    append: yes
- name: Create traefik configuration directory
  become: true
  file:
    path: "{{item}}"
    state: directory
    mode: 0755
    owner: traefik
    group: traefik
  with_items:
    - /etc/traefik
    - /etc/traefik/rules
