---
- name: Install nginx
  become: true
  apt:
    name: nginx-full
    state: latest
- name: Start nginx
  become: true
  service:
    name: nginx
    state: started
- name: Add certbot repositories
  become: true
  apt_repository:
    repo: ppa:certbot/certbot
- name: Install certbot
  become: true
  apt:
    name: python-certbot-nginx
    state: latest
    update_cache: yes
- name: Generate dhparams
  shell: openssl dhparam -out /etc/nginx/dhparams.pem 2048
  args:
    creates: /etc/nginx/dhparams.pem
- name: Create letsencrypt certificate
  shell: "certbot certonly --agree-tos --nginx --email {{drone_email}} -n -d {{drone_domain}}"
  args:
    creates: "/etc/letsencrypt/live/{{drone_email}}"
- name: Install nginx drone configuration
  template:
    src: templates/drone.conf.j2
    dest: /etc/nginx/sites-enabled/drone.conf
- name: Install nginx system configuration
  template:
    src: templates/nginx.conf
    dest: /etc/nginx/nginx.conf
- name: Restart nginx
  service:
    name: nginx
    state: restarted
