apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana
  namespace: monitoring
  labels:
    app: grafana
data:
  grafana.ini: |-
    instance_name = grafana.expected.sh

    [metrics]
    enabled = true
