apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana
  namespace: monitoring
  labels:
    app: grafana
data:
  grafana.ini: |-
    instance_name = grafana.expected.sh

    [server]
    root_url = http://grafana.expected.sh

    [metrics]
    enabled = true

    [security]
    admin_user = remicaumette

    [auth]
    disable_login_form = true
    oauth_auto_login = true

    [auth.github]
    enabled = true
    allow_sign_up = true
    client_id = a475cbc261d7e8de0474
    client_secret = 562e156e642a52fcbc5753237f22c60e3aa35c6a
    scopes = user:email,read:org
    auth_url = https://github.com/login/oauth/authorize
    token_url = https://github.com/login/oauth/access_token
    api_url = https://api.github.com/user
    allowed_organizations = expectedsh
