namespace: monitoring
commonLabels:
  app: grafana
resources:
  - deployment.yaml
  - ingress.yaml
  - service.yaml
  - volume.yaml
configMapGenerator:
  - name: grafana
    files:
      - config/grafana.ini
  - name: grafana-datasources
    files:
      - config/datasources.yaml
  - name: grafana-dashboards
    files:
      - config/dashboards.yaml
      - config/dashboards/kubernetes_deployments.json
      - config/dashboards/kubernetes_cluster.json
      # - config/dashboards/node_exporter.json
secretGenerator:
  - name: grafana
    commands:
      GF_AUTH_GITHUB_CLIENT_ID: "printf ${GRAFANA_CLIENT_ID}"
      GF_AUTH_GITHUB_CLIENT_SECRET: "printf ${GRAFANA_CLIENT_SECRET}"
imageTags:
  - name: grafana/grafana
    newTag: latest
