apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: grafana
  namespace: monitoring
  labels:
    app: grafana
spec:
  resources:
    requests:
      storage: 1Gi
  accessModes:
    - ReadWriteOnce
