apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres
spec:
  replicas: 1
  serviceName: postgres
  volumeClaimTemplates: []
  selector:
    matchLabels:
      app: postgres
  template:
    spec:
      securityContext:
        fsGroup: 2000
        runAsNonRoot: true
        runAsUser: 1000
      containers:
        - name: postgres
          image: postgres
          env:
            - name: POSTGRES_USER
              value: expected
            - name: POSTGRES_PASSWORD
              value: expected
            - name: POSTGRES_DB
              value: expected
            - name: PGDATA
              value: /var/lib/postgresql/data/pgdata
          ports:
            - name: postgres
              containerPort: 5432
          volumeMounts:
            - name: postgres
              mountPath: /var/lib/postgresql/data
            - name: init
              mountPath: /docker-entrypoint-initdb.d
          readinessProbe:
            tcpSocket:
              port: postgres
            initialDelaySeconds: 30
            timeoutSeconds: 30
          livenessProbe:
            tcpSocket:
              port: postgres
            initialDelaySeconds: 30
            timeoutSeconds: 30
          resources:
            limits:
              cpu: 200m
              memory: 512Mi
            requests:
              cpu: 200m
              memory: 256Mi
      volumes:
        - name: init
          configMap:
            name: postgres
        - name: postgres
          persistentVolumeClaim:
            claimName: postgres
