apiVersion: v1
kind: Service
metadata:
  name: postgres
#  annotations:
#    prometheus.io/scrape: "true"
spec:
  type: ClusterIP
  selector:
    app: postgres
  ports:
    - name: postgres
      port: 5432
      targetPort: postgres
