apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app: prometheus
  name: prometheus
  namespace: monitoring
spec:
  serviceName: prometheus
  replicas: 1
  selector:
    matchLabels:
      app: prometheus
  template:
    metadata:
      labels:
        app: prometheus
    spec:
      serviceAccountName: prometheus
      securityContext:
        fsGroup: 2000
        runAsNonRoot: true
        runAsUser: 1000
      containers:
        - name: prometheus
          image: prom/prometheus
          ports:
            - name: ui
              containerPort: 9090
          volumeMounts:
            - name: config
              mountPath: /etc/config
            - name: prometheus
              mountPath: /var/prometheus
          args:
            - --config.file=/etc/config/prometheus.yaml
            - --web.enable-lifecycle
            - --storage.tsdb.path=/var/prometheus
            - --storage.tsdb.retention=1y
      volumes:
        - name: config
          configMap:
            name: prometheus
        - name: prometheus
          persistentVolumeClaim:
            claimName: prometheus
