apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: prometheus
spec:
  replicas: 1
  serviceName: prometheus
  volumeClaimTemplates: []
  selector:
    matchLabels:
      app: prometheus
  template:
    spec:
      serviceAccountName: prometheus
      securityContext:
        fsGroup: 2000
        runAsNonRoot: true
        runAsUser: 1000
      containers:
        - name: prometheus
          image: prom/prometheus
          ports:
            - name: http
              containerPort: 9090
          volumeMounts:
            - name: config
              mountPath: /etc/prometheus
            - name: prometheus
              mountPath: /var/prometheus
          args:
            - --config.file=/etc/prometheus/prometheus.yaml
            - --web.enable-lifecycle
            - --storage.tsdb.path=/var/prometheus
            - --storage.tsdb.retention=1y
          readinessProbe:
            httpGet:
              path: /-/ready
              port: 9090
            initialDelaySeconds: 30
            timeoutSeconds: 30
          livenessProbe:
            httpGet:
              path: /-/healthy
              port: 9090
            initialDelaySeconds: 30
            timeoutSeconds: 30
          resources:
            limits:
              cpu: 200m
              memory: 1024Mi
            requests:
              cpu: 200m
              memory: 1024Mi
      volumes:
        - name: config
          configMap:
            name: prometheus
        - name: prometheus
          persistentVolumeClaim:
            claimName: prometheus
