apiVersion: v1
kind: Service
metadata:
  name: prometheus
  namespace: monitoring
  labels:
    app: prometheus
  annotations:
    prometheus.io/scrape: "true"
spec:
  type: NodePort
  selector:
    app: prometheus
  ports:
    - name: ui
      port: 9090
      targetPort: 9090
