apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: prometheus
  namespace: monitoring
  labels:
    app: prometheus
spec:
  resources:
    requests:
      storage: 5Gi
  accessModes:
    - ReadWriteOnce
