---
- hosts: master
  vars:
    domain: "{{ lookup('env', 'DOMAIN') }}"
  roles:
    - role: consul
      consul_server: true
    - role: vault
    - role: nomad
      nomad_enable_docker: false
- hosts: tools
  roles:
    - role: consul
    - role: docker
    - role: traefik
