---
- hosts: master
  vars:
    encryption_key: "{{ lookup('env', 'ENCRYPTION_KEY') }}"
  roles:
    - role: consul
      consul_server: true
      consul_encryption: "{{encryption_key}}"
    - role: nomad
      nomad_enable_docker: false
      nomad_server: true
- hosts: tools
  vars:
    domain: "{{ lookup('env', 'DOMAIN') }}"
    email: "{{ lookup('env', 'EMAIL') }}"
    encryption_key: "{{ lookup('env', 'ENCRYPTION_KEY') }}"
  roles:
    - role: consul
      consul_encryption: "{{encryption_key}}"
      consul_enable_ui: true
    - role: docker
    - role: nomad
    - role: traefik
    - role: tools
